/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Swagger Petstore 1
 * OpenAPI spec version: 1.0.0
 */

export interface PetFirstApiDTO {
  id: number;
  name: string;
  tag?: string;
}
