/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Swagger Petstore 1
 * OpenAPI spec version: 1.0.0
 */
import type { PetFirstApiDTO } from './petFirstApiDTO';

export type PetsFirstApiDTO = PetFirstApiDTO[];
