/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Swagger Petstore 2
 * OpenAPI spec version: 1.0.0
 */
import type { PetSecondApiDTO } from './petSecondApiDTO';

export type PetsSecondApiDTO = PetSecondApiDTO[];
